### ISSUE TITLE
R code clean-up tasks

### ISSUE THREAD

**Issue by jmbarbone** [JanMarvin/openxlsx2#15]
## Code clean-up

I want to use this as a reference issue for multiple code improvements/clean up.  None of these are time intensive and can provide some quick improvements for speed and memory.  These may be done in several PRs (to keep it clean), or just smaller commits.

## Todos

- [x] `append(x, y)` to `c(x, y)`
- [x] `which(grepl(x))` to `grep(x)`
- [x] `x[grepl(x)]` to `grep(x, values = TRUE)`
- [x] `for (i in 1:length(x)) ...` to `for (i in seq_along(x)) ...`
- [x] `if (length(x) > 0) ...` to `if (length(x)) ...`
- [x] `sapply(x, length)` to `lengths(x)`
- [x] ~~removing multiple empty lines~~ whitespace is whitespace
- [x] ~~formatting function params (inconsistent between functions as how line returns work)~~ (hold off until wrappers are moved around)
- [x] `sapply(x, FUN)` to `vapply(x, FUN, FUN.VALUE)` where appropriate
- [x] ~~`x <- 1; y <- 1; if (cond) x <- 2; y <- 2` to `if (cond) x <- 2; y <- 2 else x <- 1; y <- 1`~~ this will be too hard to search for
- [x] `as.character(NA)` to `NA_character_`, etc
- [x] `character(0)` to `character()`, etc
- [x] ~~use `inherits(x, "class")` rather than `"class" %in% class(x)` (substantially quicker; promotes possibility of S3 methods)~~ this will be a larger task, should be tracked elsewhere
  - this one could be potentially nasty.  I've seen some `colClasses` lists of class names that are saved and passed around and searched with, e.g., `tolower(class_name) %in% tolower(unlist(colClasses))` which I think could be improved
- [x] ~~check consistency between parameters.  IIRC there are some parameters similar names (`sheet_names`, `sheetNames` -- though not sure this is still the case) that we should keep consistent.  These could have already been fixed~~ hold off until wrappers
- [x] `file.path(tempdir(), "name")` to `tempfile("name")`
- [x] check for missed `<<-` global assignments
- [x] ~~use `setequal()` rather than `all(x %in% y) & all(y %in% x)`~~ this is from `all.equal.Workbook()` which will need more thinking (#22)
- [x] check `ifelse()`; rarely needed unless doing something special (e.g., `ifelse(c(TRUE, TRUE, FALSE), 1:3, 0)`)
- [x] simplify options (e.g., `op <- set_options(); on.exit(options(op))`
- [x] create `unapply()` as a wrapper for `unlist(lapply(x, FUN, ...), use.names = FALSE)` -- less space
- [x] create `reg_match() <- function(x, pat) regmatches(x, gregexpr(pat, x, perl = TRUE))[[1]]`
  - [x] maybe even `apply_reg_match() <- function(x, pat) unapply(x, reg_match, pat = pat)`
