### ISSUE TITLE
Roadmap for release 0.4

### ISSUE THREAD

**Issue by JanMarvin** [JanMarvin/openxlsx2#425]
This will be release 0.4 A release with moderate new features such as `customXml` support and minor bugfixes and should be the third released to CRAN.

Initially i was planing with a new release after Christmas holidays, but the speedups in #423 and the already merged PR justify an earlier release. I'm currently planing with a release at the end of the month.

# open pull requests to merge
* [x] #424 (could use some more QA testing)
* [x] #423 (could use some more QA testing) 
* [x] #410 
* [x] #399 

# issues to work on pre release
* [x] #378 (do you want to  have a look at this @jmbarbone or shall we simply close this issue?)
* [x] #393 (haven't heard back from @ycphs, but I have a look and open a PR for this)
* [x] #449 
* [x] ~~#412~~ #451

**Comment by JanMarvin** [comment]
We are on the finish line for 0.4. There are just two minor PR to merge, #399 and #440. Other than that we are in good shape and should be able to release this week.

**Comment by JanMarvin** [comment]
Now that `mschart` 0.4 has been released to CRAN I'm wiling to see if I can squeeze in a short time frame to include #449 and #412. #449 provides some extended `add_drawing()` features #412 can use, though I already had a few other plans (aside from working on charts).

**Comment by JanMarvin** [comment]
If all goes well, #451  is the last open PR to be merged prior the 0.4 release.
