### ISSUE TITLE
`wbWorkbook` methods relocation

### ISSUE THREAD

**Issue by jmbarbone** [JanMarvin/openxlsx2#55]
List of functions that may be able to be moved from the `wbWorkbook` class to another class.  Suggestions welcomed.  Most of these seem to be better suited for the `wbWorksheet()` class on very quick inspection.

## Todos

* `wbWorksheet`
  - [ ] `setSheetName()` (add to `initialize()`
  - [ ] `setRowHeights()` (consider `options()` setting? (yes!)
    * requires rework of `rowHeights`, currently public field and can probably be changed to private
    * `rowHeights` is accessed during `setRowHeights()`, `addWorksheet()`, `cloneWorksheet()` (which should be simplified) `removeWorksheet()`, and `print()` -- but how is it brought into the final xml?
  - [ ] `createCols()`
  - [ ] `groupCols()` (is there _ungrouping_?)
  - [ ] `groupRows()`
  - [ ] `dataValidation()` -- how might we deal with list validations that are stored in separate worksheets?  Possibly require a `wbWorksheet()` object be referenced (created before) the new `wbWorksheet()` that uses the list?
  - [ ] `dataValidation_list()`
  - [ ] `conditionalFormatting()` 
  - [ ] `mergeCells()` (rename `cellMergeAdd()`?)
  - [ ] `removeCellMerge()` (rename `cellMergeRemove()`?)
  - [ ] `freezePanes()`
  - [ ] `insertImage()`(Even though this one looks like a candidate, it places images in media and needs access to Content_Type. Requires to split the wb-function into separate parts.)
  - [ ] `addStyle()`
  - [x] ~~`conditionalFormatCell()`~~ this is deprecated
* _None_ : No assignments made, can be safely extracted
  - [ ] `validateSheet()`
  - [ ] `validate_table_name()`
  - [ ] `check_overwrite_tables()`
* Unsure
  - [ ] `buildtable()` -- need to look into this more

Probably related to #34
