### ISSUE TITLE
simplify wrappers

### ISSUE THREAD

**Issue by jmbarbone** [JanMarvin/openxlsx2#75]
Simplify wrappers to just wrappers.  Move functionality into the R6 methods.

Clean up the methods a bit.

## functions

Probably some renaming to be consistent.  May need a few more `wb_get_*()` wrappers to be consistent.

- [x] `createWorkbook()` ... `wb_workbook()`
- [x] worksheets
  - [x] `addWorksheet()` ... `wb_add_worksheet()`
  - [x] `cloneWorksheet()` ... `wb_clone_worksheet()`
- [x] ~chart sheets~
  - [x] ~`addChartSheet()` ... `wb_add_chartsheet()`~
- [x] `saveWorkbook()` ... `wb_save()`
- [x] sheet names
  - [x] `getSheetName()` ... `wb_get_sheet_name()`
- [x] creators
  - [x] `addCreators()` ... `wb_add_creators()`
  - [x] `getCreators()` ... `wb_get_creators()`
  - [x] `wb_set_creators()`
  - [x] `wb_remove_creators()`
  - [x] combine documentation
- [x] `addStyle()` &#8594; handled by manager?
- [x] `freezePane()` &#8594; `ws_freeze_pane()` move to worksheet?
- [x] heights and rows
  - [x] `setRowHeights()` &#8594;  `ws_set_row_heights()`
  - [x] `setColwidths()` &#8594; `ws_set_col_widths()`
  - [x] `wbWorkbook$setColWidths()` needed
  - [x] `removeColWidths()`  &#8594; `ws_remove_col_widths()`
  - [x] `wbWorkbook$removeColWidths()` needed
  - [x] `removeRowHeights()` &#8594; `ws_remove_row_heights()`
  - [x] `wbWorkbook$removeRowHeights()` needed
- [x] plots and images
  - [x] `insertPlot()` &#8594; `wb_add_plot()`
  - [x] `wbWorkbook$insertPlot()` needed as a wrapper for `wbWorkbook$insertImage()`
- [ ] styles
  - [ ] `replaceStyle()` &#8594; handled by manager?
  - [ ] `wbWorkbook$replaceStyle()` needed
  - [ ] `getStyles()` &#8594; handled by manager?
- [x] worksheets
  - [x] `cloneWorksheet()` &#8594; `wb_clone_worksheet()`
  - [x] `removeWorksheet()` &#8594; `wb_remove_worksheet()`
  - [x] `wbWorkbook$removeWorksheet()` needed
- [x] modify base font
  - [x] `modifyBaseFont()` &#8594; `wb_set_base_font()`
  - [x] `wbWorkbook$modifyBaseFont()` needed
- [ ] header, footer
  - [x] `setHeaderFooter()` &#8594; `wb_set_header()`, `wb_set_footer()`, `ws_set_header()`, `ws_set_footer()`
  - [ ] `wbWorkbook$setHeader()` needed?
  - [ ] `wbWorkbook$setFooter()` needed?
  - [ ] might be easier to separate these?
- [x] page setup
  - [x] `pageSetup()` &#8594; `wb_page_setup()`, `ws_page_setup()`
  - [x] `wbWorkbook$pageSetup()` needed
- [ ] protection
  - [ ] `protectWorksheet()` &#8594; `wb_protect_sheets()`, `ws_protect()`, `wb_unprotect_sheets()`, `ws_unprotect()`
  - [ ] `protectWorkbook()` &#8594; `wb_protect()`, `wb_unprotect()`
- [ ] grid lines
  - [ ] `showGridLines()` &#8594; `ws_grid_lines()`, `wb_grid_lines()`
  - [ ] `wbWorkbook$showGridLines()` needed
- [ ] `worksheetOrder()` &#8594; `wb_worksheet_order()`
- [ ] `worksheetOrder<-` &#8594; necessary?
- [ ] `createNamedRegion()` &#8594; `wb_new_named_region()`
- [ ] Filters
  - [x] `addFilter()` &#8594; `wb_set_filter()`, `ws_set_filter()
  - [x] `removeFilter()` &#8594; `wb_remove_filter()`, `ws_remove_filter()`
  - [ ] `wbWorkbook$addFilter()` needed
  - [ ] `wbWorkbook$removeFilter()` needed
- [ ] `dataValidation()` &#8594; `wb_set_data_validation()`, `ws_data_validation()`
- [ ] sheet visibility
  - [ ] `sheetVisibility()` &#8594; `wb_sheet_visibility()`
  - [ ] `sheetVisibility<-` &#8594; necessary?
  - [ ] `wbWorkbook$sheetVisibility()` needed
- [ ] page break
  - [ ] `pageBreak()` &#8594; `wb_set_page_break()`
  - [ ] `wbWorkbook$pageBreak()` needed
- [ ] `copyWorkbook()` &#8594; `wb_copy()` -- will this just be `wb$clone()`?
- [ ] tables
  - [ ] `getTables()` &#8594; `wb_get_tables()`
  - [ ] `removeTable()` &#8594; `wb_remove_tables()`
  - [ ] `wbWorkbook$getTables()` needed
  - [ ] `wbWorkbook$removeTables()` needed
- [ ] groups
  - [x] `groupColumns()` &#8594; `wb_group_columns()`, ~`ws_group_columns()`~
  - [x] `groupRows()` &#8594; `wb_set_group_rows()`, ~`ws_set_group_rows()`~
  - [ ] `ungroupRows()` &#8594; `wb_remove_group_rows()`, `ws_remove_group_rows()`
- [ ] `insertImage()` &#8594; `wb_add_image()`, `ws_add_image()`; `wb_remove_image()`, `ws_remove_image()`

**Comment by JanMarvin** [comment]
I'm closing this. It's now outdated and pending for quite some time and at the moment unlikely to be picked up. Though just looking at this is a good reminder how time files. We've come a long way :)
