### ISSUE TITLE
`R6` clean up

### ISSUE THREAD

**Issue by jmbarbone** [JanMarvin/openxlsx2#9]
A list of things to do to clean up the reference classes:

## Related tasks

- [ ] #55 
- [ ] #75 

## Todos

- [x] rename files to something more appropriate (e.g., `class-workbook.R`, `class-comment.R`)
- [x] use `.self$object <- value` rather than `object <<- value` (works the same and makes for a quicker transition to R6)
- [x] move all functional methods _inside_ the Class definitions (these do no need to be separate lines or worse, separate files; these can be assigned when the class object is created)
- [x] move _wrapper_ functions inside class `.R` file or a specific `class-*-wrappers.R` file (should help reduce the side of `wrappers.R` to keep track of them
- [x] make simple utils for class checking (e.g., `is_workbook()`, `is_worksheet()`)
- [x] most methods should return with `invisible(.self)` rather than an arbitrary `invisible(1)` or `invisible(0)`
  - IMO, anything that alters `.self` should return `.self`.  Anything that's returned can be saved as a field and called afterwards (e.g., `Workbook$do_thing()$thing`)
  - could simplify wrappers that make repeated calls to object functions 
- [x] rename some methods to add action words (e.g., `conditionalFormatting()` to `setConditionalFormatting()`); some of these have _conflicts_ with fields
- [x] pull out functional methods that have no assignment/changes to `self`
  - [x] `wbWorkbook$validateSheet()`
  - [x] `wbWorkbook$createFontNode()`
  - [x] `wbWorkbook$validate_table_name()`
  - [x] `wbWorkbook$check_overwrite_tables()`
- [x] make `private$append(field, value)` functions for easier `self$field <- c(self$field, value)`

## Wrapper updates

simplify wrappers and move the heavy lifting to inside the methods (e.g., `createComment()` has checks in it that could be moved to `Comment$initialize()`, and this just becomes a wrapper; and `writeComment()` modifies the workbook so it could be `Workbook$addComment()`

For each wrapper (where applicable):
* `wb_*_get()` (returns value)
* `wb_*_set()` 
* `wb_*_add()` 
* `wb_*_remove()` 
* combine documentation
* include `#' @family wrappers`
* very simple
  * assert workbook
  * `wb$copy()$fun(params)` or `wb$field`

Tracking the work in the [r6-classes](https://github.com/JanMarvin/openxlsx2/commits/r6-classes) branch

**Comment by JanMarvin** [comment]
closing this. guess we stick with what we have
